### ISSUE TITLE
Dynamically change resolution

### ISSUE THREAD

**Issue by lolgesten** [ralfbiedert/openh264-rs#44]
Hi! Thanks for making this nice wrapper!

We got our own wrapper that I'm considering getting rid of in favor of yours, however to do so we need to be able to dynamically change the resolution on the fly. We do this by delaying the initialization (`raw_api.initialize_ext`) until we see the first frame. And when the frame resolution changes, we call `InitializeExt` again – a use case openh264 supports.

Would you be open to a PR doing something along these lines?

**Comment by ralfbiedert** [comment]
Yes absolutely, dynamic resolution support would be great!
