### ISSUE TITLE
Only the first frame is decoded successfully!

### ISSUE THREAD

**Issue by xlievo** [ralfbiedert/openh264-rs#55]
Only the first frame decoded successfully, subsequent frames failed, probably what is the reason? 
Does it have something to do with initialization Settings or capacity?
It is worth mentioning that all frames can be successfully decoded with other openh264 wrappers.

In addition, can you set some parameters for initialization?
I hope to align with other openh264 wrapper libraries to further find out why.

**Comment by xlievo** [comment]
Close the issue temporarily until someone brings it up again !

**Comment by xlievo** [comment]
Close the issue temporarily until someone brings it up again !

**Comment by ralfbiedert** [comment]
It's hard to tell without the actual .h254 file. I recommend to download a H264 Analyzer and look at your stream. Posting the code you used would be good, too.
